---
--- Generated by Luanalysis
--- Created by DELL.
--- DateTime: 2026/4/21 20:44
---
-- KEYS[1] = rate_limit:{key}:tokens
-- KEYS[2] = rate_limit:{key}:last_time
-- ARGV[1] = 每秒放令牌速率 (rate)
-- ARGV[2] = 桶最大容量 (capacity)
-- ARGV[3] = 当前时间戳毫秒 (now)
-- ARGV[4] = 请求消耗令牌数 (通常是1)

local tokens_key = KEYS[1]
local last_time_key = KEYS[2]

local rate = tonumber(ARGV[1])
local capacity = tonumber(ARGV[2])
local now = tonumber(ARGV[3])
local requested = tonumber(ARGV[4])

-- 读当前状态（不存在则用默认值）
local last_tokens = tonumber(redis.call("GET", tokens_key))
if last_tokens == nil then
    last_tokens = capacity  -- 第一次：桶是满的
end

local last_time = tonumber(redis.call("GET", last_time_key))
if last_time == nil then
    last_time = now
end

-- 计算应补充的令牌数
local elapsed = math.max(0, now - last_time)           -- 经过的毫秒数
local new_tokens = elapsed * rate / 1000               -- 新增令牌（rate是每秒）
local current_tokens = math.min(capacity, last_tokens + new_tokens) -- 当前令牌数必须小于桶大小

-- 判断是否允许
local allowed = 0
if current_tokens >= requested then
    current_tokens = current_tokens - requested
    allowed = 1
end

-- 回写状态，TTL设长一点避免key消失
local ttl = math.ceil(capacity / rate) * 2
redis.call("SET", tokens_key, current_tokens, "EX", ttl)
redis.call("SET", last_time_key, now, "EX", ttl)

return allowed  -- 1=允许 0=拒绝