---
--- Generated by Luanalysis
--- Created by DELL.
--- DateTime: 2026/4/26 17:15
---
local stock = tonumber(redis.call("GET",KEYS[1]))
--获取当前库存 如果库存为null或者已经为0 不允许扣减
if stock == nil or stock < 0 then
    return 0
end
-- redis唤起自减函数给库存-1
-- 原来没加双引号。。。。
redis.call("INCR",KEYS[1])
--stock = DECR(stock)
return 1